#include "stdafx.h"

#define GAME_TITLE "RG2R"
#define BACKGROUND_COLOR 0x00000000

#define WINDOW_DEFAULT_WIDTH 1280
#define WINDOW_DEFAULT_HEIGHT 720
#define WINDOW_START_FULLSCREEN false
#define WINDOW_RESIZABLE false
#define WINDOW_EXIST_MINIMIZEBOX true
#define WINDOW_EXIST_MAXIMIZEBOX false
#define WINDOW_EXIST_CLOSEBOX true

#define INCH_PER_DISTANCE 128
#define DIAGONAL_LENGTH 12