#include "stdafx.h"

#define GAME_TITLE "Test Title"
#define BACKGROUND_COLOR 0xff000000

#define WINDOW_DEFAULT_WIDTH 1280
#define WINDOW_DEFAULT_HEIGHT 720
#define WINDOW_START_FULLSCREEN false
#define WINDOW_RESIZABLE false
#define WINDOW_EXIST_MINIMIZEBOX false
#define WINDOW_EXIST_MAXIMIZEBOX false
#define WINDOW_EXIST_CLOSEBOX true

#define INCH_PER_DISTANCE 64
#define DIAGONAL_LENGTH 12